name: DevOpsPipeline
on:
  push:
    branches: [master]
    
jobs:
  Setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v2
    - name: setup java JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: "1.8"
    - name: maven clean
      run: mvn -B clean --file pom.xml
  Compile:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
    - uses: actions/checkout@v2
    - name: setup java JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven compile
      run: mvn -B compile --file pom.xml
  # StaticAnalysis:
  #   runs-on: ubuntu-latest
  #   needs: Compile
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: setup java JDK 17
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: 17
  #       distribution: "temurin"
  #   - name: Sonarcloud scan
  #     env:
  #       SONAR_TOKEN: ${{secrets.SATOKEN}}
  #       GITHUB_TOKEN: ${{secrets.GATOKEN}}
      # run: mvn -B verify sonar:sonar      
  UnitTestingAndCodecoverage:
    runs-on: ubuntu-latest
    needs: Compile
    permissions:
      contents: read
      packages: write
      checks: write
    steps:
    - run: echo should run unit tests
    - uses: actions/checkout@v2
    - name: maven Test
      run: mvn -B test --file pom.xml
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.9
      with:
       files: "target/surefire-reports/*.xml"
    - name: maven code coverage
      run: mvn -X org.jacoco:jacoco-maven-plugin:report
  war:
    runs-on: ubuntu-latest
    needs: UnitTestingAndCodecoverage
    permissions:
      contents: read
      packages: write
      checks: write
    steps:
    - run: echo should run unit tests
    - uses: actions/checkout@v2
    - name: maven War
      run: mvn -X war:war
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: target/*.war
  Publish:
    runs-on: ubuntu-latest
    needs: war
    steps:
    - uses: actions/checkout@v4
    - name: setup java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: "temurin"
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: target/
    - name: Publish to GitHub package
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
