name: DevOpsPipeline
on:
  push:
    branches: [master]
    
jobs:
  Setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v2
    - name: setup java JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: "1.8"
    - name: maven clean
      run: mvn -B clean --file pom.xml
  Compile:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
    - uses: actions/checkout@v2
    - name: setup java JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven compile
      run: mvn -B compile --file pom.xml
  UnitTestingAndCodecoverage:
    runs-on: ubuntu-latest
    needs: Compile
    permissions:
      contents: read
      packages: write
      checks: write
    steps:
    - run: echo should run unit tests
    - uses: actions/checkout@v2
    - name: maven Test
      run: mvn -B test --file pom.xml
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.9
      with:
       files: "target/surefire-reports/*.xml"
    - name: maven code coverage
      run: mvn -X org.jacoco:jacoco-maven-plugin:report
  war:
    runs-on: ubuntu-latest
    needs: Compile
    permissions:
      contents: read
      packages: write
      checks: write
    steps:
    - run: echo should run unit tests
    - uses: actions/checkout@v2
    - name: maven War
      run: mvn -X war:war
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: target/*.war
