# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CICD Pipeline

on:
  push:
    branches: [master]

jobs:
  Setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDk 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven job
      run: mvn -B clean --file pom.xml
  Compile:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDk 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven job
      run: mvn -B compile --file pom.xml
  UnitTesting:
   runs-on: ubuntu-latest
   needs: Compile
   permissions:
      contents: read
      packages: write
      checks: write
   steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: maven job
      run: mvn -B test --file pom.xml
    - name: Publish test result
      uses: Enricomi/publish-unit-test-result-action@v1.9
      with:
        files: "target/surefire-reports/*.xml"
  CodeCoverage:
   runs-on: ubuntu-latest
   needs: UnitTesting
   permissions:
      contents: read
      packages: write
      checks: write
   steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: maven job
      run: mvn -X org.jacoco:jacoco-maven-plugin:report
  War:
    runs-on: ubuntu-latest
    needs: CodeCoverage
    steps:
    - uses: actions/checkout@v1
    - name: maven job
      run: mvn -X war:war
      
    
      
      
    
  


  #   - name: Publish to GitHub Packages Apache Maven
  #     run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
  #     env:
  #       GITHUB_TOKEN: ${{ github.token }}
